### ISSUE TITLE
can not find the button of the add-to-snippet

### ISSUE THREAD

**Issue by nir-Visual3d** [luliangce/AddToSnippet#1]
also, explanation, example and docomentation are missing to instruct the plugin's flow. 

is it in the right click menu?
top bar?
nowhere to check

**Comment by mellmo** [comment]
Hi @nir-Visual3d 

It should be solved by the following [pull request](https://github.com/luliangce/AddToSnippet/pull/3/files)

In the meantime, to use the extension:
 - Select the text you want to add as a snippet
 - press `Ctrl + Shift + P`
 - Type `Add-To-Snippet`

That should do it

**Comment by luliangce** [comment]
this shoud be solved, thanks for your answer!
@nir-Visual3d
